{% set name = "wikipedia_ql" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wikipedia_ql-{{ version }}.tar.gz
  sha256: c13cd54544577eb095a0adcfcbc295190d75469425d76b9629a516fd24be7abe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - pip
    - python >=3.7
  run:
    - bs4
    - lark-parser
    - nltk
    - python >=3.7
    - requests

test:
  imports:
    - wikipedia_ql
    - nltk
  source_files:
    - tests
  commands:
    - python -c "import nltk; nltk.download('punkt')"
    - pytest tests
  requires:
    - pytest

about:
  home: https://github.com/zverok/wikipedia_ql
  summary: Query Language for Wikipedia
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
