{% set name = "wikipedia_ql" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wikipedia_ql-{{ version }}.tar.gz
  sha256: e1dccb63e50de0781e7d84edd1b6fff63d842489c1afe15738764fdbb0149b0c

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - pip
    - python >=3.7
  run:
    - bs4 >=0.0.1
    - beautifulsoup4 >=0.0.1
    - lark >=0.11.3,<0.12.0
    - nltk >=3.6.2
    - python >=3.7
    - requests >=2.25.1
    - soupsieve >=2.3.1

test:
  imports:
    - wikipedia_ql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zverok/wikipedia_ql
  summary: Query Language for Wikipedia
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
