{% set name = "wikipedia_ql" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wikipedia_ql-{{ version }}.tar.gz
  sha256: 6f78987f526b6fe36b425c2b1d424bc6e078fd0ef436a46c431bc6af14cc82df

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - pip
    - python >=3.7
  run:
    - bs4 >=0.0.1
    - lark >=0.11.3,<0.12.0
    - nltk >=3.6.2
    - python >=3.7
    - requests >=2.25.1
    - soupsieve >=2.3.1

test:
  imports:
    - wikipedia_ql

about:
  home: https://github.com/zverok/wikipedia_ql
  summary: Query Language for Wikipedia
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
